// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "davidleitw",
            "email": "davidleitw@gmail.com"
        },
        "license": {
            "name": "Apache 2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/calendar/{ID}/createNewEvent": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Calendar"
                ],
                "summary": "創建事件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "填入事件標題",
                        "name": "Title",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "填入事件開始時間",
                        "name": "StartTime",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "填入事件的結束時間",
                        "name": "EndTime",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "填入事件想要提前幾分鐘提醒 以-3h這種形式",
                        "name": "RemindTime",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "填入事件內容",
                        "name": "Context",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {},
                    "400": {},
                    "500": {}
                }
            }
        },
        "/api/calendar/{ID}/deleteEvent": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Calendar"
                ],
                "summary": "刪除指定的事件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "填入想要刪除事件的標題",
                        "name": "title",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "填入想要刪除事件的開始時間",
                        "name": "start_time",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "填入想要刪除事件需要提前幾分鐘提醒 以-3h這種形式填入(創建事件要填的那個寫法)",
                        "name": "remind_time",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {},
                    "500": {}
                }
            }
        },
        "/api/calendar/{ID}/getAllEvent": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Calendar"
                ],
                "summary": "登入時該用戶所有資料的概要",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/serialization.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/serialization.Response"
                        }
                    }
                }
            }
        },
        "/api/calendar/{ID}/getEventInfo": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Calendar"
                ],
                "summary": "獲得某個特定事件的資料",
                "parameters": [
                    {
                        "type": "string",
                        "description": "填入想要查詢事件的標題",
                        "name": "title",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "填入想要查詢事件的開始時間",
                        "name": "start_time",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "填入想要查詢事件需要提前幾分鐘提醒 以-3h這種形式填入(創建事件要填的那個寫法)",
                        "name": "remind_time",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {},
                    "500": {}
                }
            }
        },
        "/api/calendar/{ID}/updateEvent": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Calendar"
                ],
                "summary": "更新某個事件的內容",
                "parameters": [
                    {
                        "type": "string",
                        "description": "填入修改前的事件標題",
                        "name": "OldTitle",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "填入修改前的開始時間",
                        "name": "OldStart",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "填入修改前的欲提醒時間",
                        "name": "OldRemind",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "填入修改後的新標題",
                        "name": "Title",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "填入修改後的新開始時間",
                        "name": "StartTime",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "填入修改後的新結束時間",
                        "name": "EndTime",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "填入修改後的新提醒時間 以-3h這種形式",
                        "name": "RemindTime",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "填入修改後的事件內容",
                        "name": "Context",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "填入修改後的參考網址",
                        "name": "ReferenceUrl",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {},
                    "500": {}
                }
            }
        },
        "/api/user/userLogin": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "用戶登入",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用戶電子信箱(帳號)",
                        "name": "account",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用戶密碼",
                        "name": "password",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/serialization.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/serialization.Response"
                        }
                    }
                }
            }
        },
        "/api/user/userLogout": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "用戶登出",
                "responses": {
                    "200": {
                        "description": "登出成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/serialization.Response"
                        }
                    }
                }
            }
        },
        "/api/user/userRegister": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "用戶註冊",
                "parameters": [
                    {
                        "type": "string",
                        "description": "填入用戶的電子信箱",
                        "name": "UserMail",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "填入用戶的使用者名稱 可隨時更改",
                        "name": "UserName",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "填入用戶的密碼 需要八碼以上",
                        "name": "UserPass",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密碼確認, 需要UserPass參數相同",
                        "name": "UserPassConfirm",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用戶的電話號碼 如果使用者沒填 前端會補上00000000",
                        "name": "USerRid",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/serialization.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/serialization.Response"
                        }
                    }
                }
            }
        },
        "/api/user/usercheckLogin": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "確認登入狀態",
                "responses": {
                    "200": {
                        "description": "false",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "serialization.Response": {
            "type": "object",
            "additionalProperties": true
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.0.1",
	Host:        "http://espresso.nctu.me:8080/",
	BasePath:    "/api/",
	Schemes:     []string{},
	Title:       "Espresso Example API File",
	Description: "Expreesso calendar的api文檔, 方便串接前後端",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
